import { useState } from 'react'
import Head from 'next/head'
import Layout from '@/components/layout'
import Hero from '@/components/hero'
import Clients from '@/components/clients'
import Services from '@/components/services'
import Work from '@/components/work'

export default function Home () {
  const [cart, setCart] = useState([])
  const addToCart = (service) => {
    if (cart.includes(service)) {
      setCart(cart.filter(allService => allService !== service))
      return false
    }
    setCart([...cart, service])
  }
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout cart={cart}>
        <Hero />
        <Clients />
        <Services addToCart={addToCart} cart={cart} />
        <Work />
      </Layout>
    </>
  )
}
