import Head from 'next/head'
import Layout from '@/components/layout'
import Hero from '@/components/hero'
import Clients from '@/components/clients'

export default function Home () {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <Hero />
        <Clients />
      </Layout>
    </>
  )
}
