import Head from 'next/head'
import Layout from '@/components/layout'
import Image from 'next/image'
import styles from '@/styles/Works.module.css'
import Link from 'next/link'

export default function Home ({ data }) {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout cart=''>
        <h1>All my Works</h1>
        <div className={styles.works}>
          {
            data.map((work) => {
              return (
                <div key={work.id} className={styles.work}>
                  <Link href={`work/${work.id}`}>
                    <Image src={work.thumbnailUrl} width='150' height='150' alt='My Work' />
                    <h3>{work.title}</h3>
                  </Link>
                </div>
              )
            })
          }
        </div>
      </Layout>
    </>
  )
}

export async function getStaticProps () {
  try {
    const response = await fetch('https://jsonplaceholder.typicode.com/photos')
    let data = await response.json()
    data = data.slice(0, 15)
    return {
      props: {
        data
      }
    }
  } catch (error) {
    console.log(error)
  }
}
